apiVersion: v1
kind: Service
metadata:
  name: hcatalog-for-dev
  labels:
    name: hcatalog
spec:
  ports:
    - port: 9083
      name: metaserver
    - port: 10002
      name: hive
    - port: 9000
      name: node
    - port: 10000
      name: data
    - port: 50075
      name: web
  selector:
    name: hcatalog
  type: LoadBalancer

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: hcatalog
spec:
  replicas: 1
  selector:
    name: hcatalog
  template:
    metadata:
      name: hcatalog
      labels:
        name: hcatalog
    spec:
      containers:
        - name: hadoop-master
          image: teradatalabs/cdh5-hive
          ports:
            - name: metaserver
              containerPort: 9083
            - name: hive
              containerPort: 10002
            - containerPort: 9000
              name: node
            - containerPort: 10000
              name: data
            - containerPort: 50075
              name: web
